fantasy3movies/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('movies/', views.movies_index, name='index' ),
    path('movies/<int:movie_id>/', views.movies_detail, name='detail'),
    path('movies/add/', views.AddMovie.as_view(), name='add_movie'),
    path('movies/actor/', views.AddActor.as_view(), name='actors'),
    path('movies/production/', views.AddProd_Mem.as_view(), name='production'),
    path('accounts/signup/', views.signup, name='signup'),
    path('movies/actor/<int:pk>/delete/', views.DeleteActor.as_view(), name='delete_actor'),
    path('movies/prod_mem/<int:pk>/delete/', views.DeleteProd.as_view(), name='delete_prod'),
    path('movies/<int:pk>/delete/', views.DeleteMovie.as_view(), name='delete_movie'),
    path('movies/<int:pk>/edit', views.MovieUpdate.as_view(), name="update"),
    path('movies/poster', views.poster_search, name='poster'),
    path('movies/search/', views.search, name='search'),
    path('search/<int:result_id>', views.search_id, name='search_id'),
    path('movies/poster/add', views.add_poster, name="add_poster")
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.core.validators import RegexValidator

# Create your models here.
GENRES = (
    ('1', 'Action'),
    ('2', 'Adventure'),
    ('3', 'Animation'),
    ('4', 'Comedy'),
    ('5', 'Crime'),
    ('6', 'Documentary'),
    ('7', "Drama"),
    ('8', 'Fantasy'),
    ('9', 'Horror'),
    ('10', 'Musical'),
    ('11', 'Mystery'),
    ('12', 'Romance'),
    ('13', 'Science Fiction'),
    ('14', 'Thriller'),
    ('15', 'War'),
    ('16', 'Western')
)

ROLES = (
    ('D', 'Director'),
    ('S', 'Screen Writer'),
    ('P', 'Producer')
)

class Prod_Mem(models.Model):
    role = models.CharField(
        max_length=1,
        choices=ROLES
    )
    name = models.CharField(max_length=25)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('production')

class Actor(models.Model):
    name = models.CharField(max_length=25)
    dob = models.DateField()
    nationality = models.CharField(max_length=25)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('actors')
    
class Movie(models.Model):
    name = models.CharField(max_length=100)
    genre = models.CharField(
        max_length=2,
        choices=GENRES,
    )
    description = models.TextField(max_length=500)
    movie_poster = models.CharField(max_length=100, null=True)
    release_year = models.IntegerField(
    validators=[
        RegexValidator(
            regex=r'^19\d{2}|20[0-4]\d$', 
            message="Enter a valid year between 1900 and 2049",
        ),
    ],
    error_messages={
        'invalid': 'Enter a valid year between 1900 and 2049',
    }
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    prod_mem = models.ManyToManyField(Prod_Mem)
    actor = models.ManyToManyField(Actor)
    


    def __str__(self):
        return f'{self.name} ({self.id})'
    
    def get_absolute_url(self):
        return reverse('detail', kwargs = {'movie_id': self.id})

main_app/forms.py
from django.forms import ModelForm
from .models import Movie, Actor, Prod_Mem
from django import forms

class MovieForm(ModelForm):
    class Meta:
        model = Movie
        fields = ['genre']

class AssocActorForm(forms.Form):
    actors = forms.ModelChoiceField(queryset = Actor.objects.all())
    
class AssocCrew(forms.Form):
    crew = forms.ModelChoiceField(queryset=Prod_Mem.objects.all())

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Movie, Actor, Prod_Mem
from .forms import AssocActorForm, AssocCrew
from django.views.generic import DeleteView, UpdateView
import requests, os
from datetime import datetime



def home(request):
    return render(request, 'home.html')

@login_required
def movies_index(request):
    movies = Movie.objects.filter(user=request.user)
    return render(request, 'movies/index.html', {
       'movies': movies
    })

def poster_search(request):
   return render(request, 'movies/poster.html')

@login_required
def movies_detail(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    
    if request.method == 'POST':
      actor_form = AssocActorForm(request.POST)
      if actor_form.is_valid():
        selectedActor = actor_form.cleaned_data["actors"]
        movie.actor.add(selectedActor)
        return redirect ('detail', movie_id=movie_id)
      
      crew_form = AssocCrew(request.POST)
      if crew_form.is_valid():
         selectedCrew = crew_form.cleaned_data["crew"]
         movie.prod_mem.add(selectedCrew)
         return redirect ('detail', movie_id=movie_id)
    else:
      actor_form = AssocActorForm(request.POST)
      crew_form = AssocCrew(request.POST)
      actors_in_movie = movie.actor.all()
      actors_not_in_movie = Actor.objects.exclude(id__in=movie.actor.all().values_list('id'))
      crew_in_movie = movie.prod_mem.all()
      crew_not_in_movie = Prod_Mem.objects.exclude(id__in=movie.prod_mem.all().values_list('id'))
  

      return render(request, 'movies/detail.html', {
        'movie': movie,
        'actors_not_in_movie': actors_not_in_movie, 
        "actor_form": actor_form,
        "crew_form": crew_form
      })

@login_required
def search_id(request, result_id):
  movies = Movie.objects.filter(user=request.user)
  #movies = Movie.objects.all()
  api_token = os.environ.get('TMDB_API_TOKEN')
  url = f"https://api.themoviedb.org/3/movie/{result_id}"
  headers = {
    "accept": "application/json",
    "Authorization": api_token
  }
  response = requests.get(url, headers=headers)
  data = response.json()
  for result in data.get('results', []):
    formatted_release_date = datetime.strptime(result['release_date'], '%Y-%m-%d').strftime('%B %d, %Y')
    # print(formatted_release_date)
    result['formatted_release_date'] = formatted_release_date
  return render(request, 'movies/results.html', {'data': data, 'movies': movies})

@login_required
def search(request):
  api_token = os.environ.get('TMDB_API_TOKEN')
  movie_title = request.POST.get('genre')
  url = f'https://api.themoviedb.org/3/search/movie?&query={movie_title}'
  headers = {
    "accept": "application/json",
    "Authorization": api_token
  }
  response = requests.get(url, headers=headers)
  data = response.json()
  return render(request, 'movies/poster.html', {'data': data})

@login_required
def add_poster(request):
  try:
    movie_id = request.POST.get('movie')
    movie = Movie.objects.get(id=movie_id)
    movie.movie_poster = request.POST.get('poster')
    movie.save()
  except Exception as e:
    print(str(e))
  return redirect('search')
  

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

class AddMovie(LoginRequiredMixin, CreateView):
  model = Movie
  fields = ['name', 'genre', 'description', 'release_year',]

  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)

class AddActor(LoginRequiredMixin, CreateView):
  model = Actor
  fields = ['name', 'dob', 'nationality']

  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)
  
  #The Django docs say this is how you add custom data to a generic CBV
  def get_context_data(self, **kwargs):
     context = super().get_context_data(**kwargs)
     context["actor_list"] = Actor.objects.all()
     return context

class AddProd_Mem(LoginRequiredMixin, CreateView):
  model = Prod_Mem
  fields = ['name', 'role']

  def form_valid(self, form):
     form.instance.user = self.request.user
     return super().form_valid(form)
  
  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context["prod_list"] = Prod_Mem.objects.all()
    return context

class DeleteActor(LoginRequiredMixin, DeleteView):
   model = Actor
   success_url = '/movies/actor'

class DeleteProd(LoginRequiredMixin, DeleteView):
   model = Prod_Mem
   success_url = '/movies/production'

class DeleteMovie(LoginRequiredMixin, DeleteView):
   model = Movie
   success_url = '/movies'

class MovieUpdate(LoginRequiredMixin, UpdateView):
   model = Movie
   fields = ['genre', 'description', 'release_year']

main_app/templates/movies/detail.html
{% extends 'base.html' %}
{% block content %}

{% load static %}


<div class="container">
    <!-- movie title -->
    <div class="row">
        <div class="col">
            <h2 class="movie_title">{{ movie.name }}</h2>
            <hr />
        </div>
    </div>
    <!-- movie poster and movie info -->
    <div class="row"> 
        <div class="col-md-6">
            <div class="card border border-secondary" style="width: 100%">
                {% if movie.movie_poster %}
                <img src="{{movie.movie_poster}}" class="img-fluid card-img-top" alt="movie poster">
                {% else %}
                <img src="{% static 'img/500x735blank.png' %}" class="img-fluid card-img-top" alt="default-movie">
                <a class="card-text" href="{% url 'poster' %}">Add Your Poster Here!</a>
                {% endif %}
            </div>
        </div>

        <div class="col-md-6">
            <div class="card border border-secondary">
                <div class="card-header">
                    Movie Info
                </div>
                <div class="card-body">
                    <h6 class="card-title">Genre</h6>
                    <p class="card-text ">{{ movie.get_genre_display }}</p>
                    <h6 class="card-title">Release Year</h6>
                    <p class="card-text">{{ movie.release_year }}</p>
                    <h6 class="card-title">Synopsis</h6>
                    <p class="card-text">{{ movie.description }}</p>
                </div>
            </div>
        </div>
    </div>
    <hr />

    <div class="row">
        <!-- Current Cast -->
        <div class="col-md-6">
            <h2>{{ movie.name }} Dream Cast</h2>
            <div class="card border border-secondary">
                <div class="card-header">
                    Current Actors
                </div>
                <div class="card-body">
                    {% for actor in movie.actor.all %}
                    <ul>
                        <li>{{ actor.name }}</li>
                    </ul>
                    {% endfor %}
                </div>
            </div>
        </div>
        <!-- Current Crew -->
        <div class="col-md-6">
            <h2>{{ movie.name }} Dream Crew</h2>
            <div class="card border border-secondary">
                <div class="card-header">
                    Current Crew
                </div>
                <div class="card-body">
                    {% for prod_mem in movie.prod_mem.all %}
                    <ul>
                        <li>{{ prod_mem.name }}</li> 
                    </ul>
                    {% endfor %}
                </div>
            </div>
        </div>

    <!-- Add Cast and Crew -->
    <div class="row">
        <!-- Add Cast -->
        <div class="col-md-6">
            <h2>Add an Actor to this Movie</h2>
            <div class="card border border-secondary">
                <div class="card-header">
                        Actor Index
                </div>
                <div class="card-body">
                    <form name="AssocActors" method="POST">
                            {% csrf_token %}
                            {{ actor_form.as_p }}
                        <button type="submit">Add to Movie</button>
                    </form>
                </div>
            </div>
            <a class= 'add text-secondary' href="{% url 'actors' %}">Not listed? Add them here!</a>
        </div>
             <!-- Add Crew -->
        <div class="col-md-6">
            <h2>Add Crew</h2>
            <div class="card border border-secondary">
                <div class="card-header">
                    Crew
                </div>
                <div class="card-body">
                    <form name="AssocCrew" method="POST">
                            {% csrf_token %}
                            {{ crew_form.as_p }}
                            <button type="submit">Add to Movie</button>
                    </form>
                </div>
            </div>
                <a class= 'add text-secondary' href="{% url 'production' %}">Not listed? Add them here!</a>
        </div>
    </div>
</div>

{% endblock %}

main_app/templates/movies/index.html
{% extends 'base.html' %}
{% block content %}

<h2>Fantasy Movies List</h2>


<table class="table">
    <thead>
        <tr>
            <th>Movie</th>
            <th>Genre</th>
            <th>Release Year</th>
        </tr>
    </thead>

    <tbody>
        {% for movie in movies %}
        <tr class="index_pick" onclick="window.location='{% url 'detail' movie.id %}';" style="cursor:pointer;">
            <td>{{ movie.name }}</td>
            <td>{{ movie.get_genre_display }}</td>
            <td>{{ movie.release_year }}</td>
            <td><a href="{% url 'delete_movie' movie.id %}" class="btn btn-secondary">Delete</a></td>
            <td><a href="{% url 'update' movie.id %}" class="btn btn-secondary">Edit</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>



{% endblock %}

main_app/templates/movies/poster.html
{% extends '../base.html' %}
{% block content %}

<form action="{% url 'search' %}" method="POST">
    {% csrf_token %}
    <label for="image">Search for movie details by title:</label>
    <input type="text" name="genre">
    <input type="submit" value="Search" class="btn btn-secondary">
</form>

{% if data %}
<ul>
    {% for result in data.results %}
    <li>
        <form action="{% url 'search_id' result.id %}">
            {% csrf_token %}
            <button type="submit">View Poster for '{{ result.title }}'</button>
        </form>
        <h3>Official Synopsis:</h3>{{ result.overview }}<br>
        <h4>Released:</h4>{{ result.release_date }}
        <br><br>
    </li>
    {% endfor %}
</ul>
{% endif %}

{% endblock %}

main_app/templates/movies/results.html
{% extends 'base.html' %}
{% block content %}


<img src="https://image.tmdb.org/t/p/w600_and_h900_bestv2/{{data.poster_path}}" alt="movie_poster" style="max-width: 70vmin; max-height: 70vmin;">
<form action="{% url 'add_poster' %}" method="POST" id="poster_form">
    {% csrf_token %}
    <select name="movie" id="movie_select">
        {% for movie in movies %}
        <option value="{{movie.id}}">{{movie.name}}</option>
        {% endfor %}
    </select>
    <input type="hidden" name="poster" value="https://image.tmdb.org/t/p/w600_and_h900_bestv2/{{data.poster_path}}">
    <input type="submit" value="Add Movie">
</form>

<script>
    document.getElementById('poster_form').addEventListener('submit', (e)=>{
        const movieSelect = document.getElementById('movie_select');
        if(!movieSelect.value){
            event.preventDefault();
            alert('Please select a movie');
        }
    });
</script>

{% endblock %}